const Items = [
  {
    id: 1,
    mainImage: "https://res.cloudinary.com/dup3vhxmo/image/upload/v1718340691/SocialEcho_Main_page_q3v3pe.jpg",
    img: [
      "https://res.cloudinary.com/dup3vhxmo/image/upload/v1718340764/SocialEcho_Admin_cw88be.jpg",
      "https://res.cloudinary.com/dup3vhxmo/image/upload/v1718340781/SocialEcho_Admin2_aqe0xd.jpg",
      "https://res.cloudinary.com/dup3vhxmo/image/upload/v1718340797/SocialEcho_HomePage_zs7xoz.jpg",
      "https://res.cloudinary.com/dup3vhxmo/image/upload/v1718340808/SocialEcho_Login_bqhxzh.jpg",
      "https://res.cloudinary.com/dup3vhxmo/image/upload/v1718344449/SocialEcho_1_n70zjk.jpg",
      "https://res.cloudinary.com/dup3vhxmo/image/upload/v1718344468/SocialEcho2_dzvfz7.jpg",
      "https://res.cloudinary.com/dup3vhxmo/image/upload/v1718344479/SocialEcho3_c8t3hp.jpg",
      "https://res.cloudinary.com/dup3vhxmo/image/upload/v1718344491/SocialEcho4_oqvp45.jpg",
      "https://res.cloudinary.com/dup3vhxmo/image/upload/v1718344501/SocialEcho5_i6oqhj.jpg",
      "https://res.cloudinary.com/dup3vhxmo/image/upload/v1718344513/SocialEcho6_ovlamn.jpg",
      "https://res.cloudinary.com/dup3vhxmo/image/upload/v1718344524/SocialEcho7_vkrxon.jpg",
    ],
    features: [
      "User registration and login",
      "Authentication using JWT Tokens",
      "CRUD operations (Post create, read, update and delete)",
      "Upload user ımages and blog content  to the server",
      "Commenting on the post",
      "Responsive Design",
      "404 Page and many more.",
    ],
    technologies: [
      "React",
      "React Hooks",
      "React Icons",
      "Axios",
      "CSS",
      "UUID",
      "NodeJS",
      "ExpressJS",
      "MongoDB",
      "Mongoose",
      "Express Async Handler",
      "Json Web Token",
      "Bcryptjs",
      "Nodemailer",
      "Dontenv",
      "Slugify",
      "Cors",
    ],
    title: "Social Echo",
    description:
      "A social networking platform with automated content moderation and context-based authentication system made with MongoDB, Express, React & Nodejs (MERN)",
    //category: "personal",
    // liveLink: "https://berthutapea.vercel.app/mern-blog",
    codeLink: "https://github.com/Seemikumari/SocialEcho-Website",
  },
  {
    id: 2,
    mainImage: "https://res.cloudinary.com/dup3vhxmo/image/upload/v1719052753/Insta_UI_Home_oucpth.jpg",
    img: [
      "https://res.cloudinary.com/dup3vhxmo/image/upload/v1719052773/Insta_UI_2_r0cdhe.jpg",
      "https://res.cloudinary.com/dup3vhxmo/image/upload/v1719052796/Insta_UI_3_iblyfk.jpg",
      "https://res.cloudinary.com/dup3vhxmo/image/upload/v1719052815/Insta_UI3_pghosj.jpg",
      "https://res.cloudinary.com/dup3vhxmo/image/upload/v1719052837/Insta_UI_4_mrt4ck.jpg",
      "https://res.cloudinary.com/dup3vhxmo/image/upload/v1719053028/Insta_UI_6_bo9wey.png",
      "https://res.cloudinary.com/dup3vhxmo/image/upload/v1719053300/INSTA_UI_5_izxleo.png",
      "https://res.cloudinary.com/dup3vhxmo/image/upload/v1719053343/insta_UI_7_ipdl0a.png",
      "https://res.cloudinary.com/dup3vhxmo/image/upload/v1719053359/INSTA_UI_8_looesw.png",
      "https://res.cloudinary.com/dup3vhxmo/image/upload/v1719053419/insta_UI_9_u6t6jf.png",
      "https://res.cloudinary.com/dup3vhxmo/image/upload/v1719053434/insta_UI_10_uz22fm.png",
    ],
    features: [
      "Instagram Home Page ",
      "Profile , Explore & other  Pages",
    ],
    technologies: [
      "HTML",
      "CSS",
      "SCSS",
      "jquery",
      "owlcarousel",
      "carousel",
      "Image API",
    ],
    title: "Instagram-UI",
    description:
      "This project showcases proficiency in HTML, CSS, SCSS, and JavaScript by accurately recreating the user interface of Instagram, including its home page, profile page, explore section, and other features. ",
    // category: "personal",
    liveLink: "https://seemikumari.github.io/Instagram-UI-v2.0/",
    codeLink: "https://github.com/Seemikumari/Instagram-UI-v2.0",
  },
  // {
  //   id: 4,
  //   mainImage: "https://res.cloudinary.com/du541igfh/image/upload/v1682772430/Blog%20Portfolio%20Gilbert/Project/mern-penggajian-karyawan/img-2_vsab0u.png",
  //   img: [
  //     "https://res.cloudinary.com/du541igfh/image/upload/v1682772430/Blog%20Portfolio%20Gilbert/Project/mern-penggajian-karyawan/img-1_gywmlj.png",
  //     "https://res.cloudinary.com/du541igfh/image/upload/v1682772430/Blog%20Portfolio%20Gilbert/Project/mern-penggajian-karyawan/img-2_vsab0u.png",
  //     "https://res.cloudinary.com/du541igfh/image/upload/v1682772430/Blog%20Portfolio%20Gilbert/Project/mern-penggajian-karyawan/img-3_ktppfh.png",
  //     "https://res.cloudinary.com/du541igfh/image/upload/v1682772430/Blog%20Portfolio%20Gilbert/Project/mern-penggajian-karyawan/img-4_g9pcqp.png",
  //     "https://res.cloudinary.com/du541igfh/image/upload/v1682772430/Blog%20Portfolio%20Gilbert/Project/mern-penggajian-karyawan/img-5_cugdqq.png",
  //     "https://res.cloudinary.com/du541igfh/image/upload/v1682772430/Blog%20Portfolio%20Gilbert/Project/mern-penggajian-karyawan/img-6_d550ha.png",
  //     "https://res.cloudinary.com/du541igfh/image/upload/v1682772431/Blog%20Portfolio%20Gilbert/Project/mern-penggajian-karyawan/img-7_u2td2u.png",
  //     "https://res.cloudinary.com/du541igfh/image/upload/v1682772431/Blog%20Portfolio%20Gilbert/Project/mern-penggajian-karyawan/img-8_tt0tqg.png",
  //     "https://res.cloudinary.com/du541igfh/image/upload/v1682772431/Blog%20Portfolio%20Gilbert/Project/mern-penggajian-karyawan/img-9_thcxyv.png",
  //     "https://res.cloudinary.com/du541igfh/image/upload/v1682772431/Blog%20Portfolio%20Gilbert/Project/mern-penggajian-karyawan/img-10_wwmqty.png",
  //     "https://res.cloudinary.com/du541igfh/image/upload/v1682772431/Blog%20Portfolio%20Gilbert/Project/mern-penggajian-karyawan/img-11_issyrd.png",
  //     "https://res.cloudinary.com/du541igfh/image/upload/v1682772431/Blog%20Portfolio%20Gilbert/Project/mern-penggajian-karyawan/img-12_visvli.png",
  //     "https://res.cloudinary.com/du541igfh/image/upload/v1682772431/Blog%20Portfolio%20Gilbert/Project/mern-penggajian-karyawan/img-13_dqy6wg.png",
  //     "https://res.cloudinary.com/du541igfh/image/upload/v1682772431/Blog%20Portfolio%20Gilbert/Project/mern-penggajian-karyawan/img-14_kvaem7.png",
  //     "https://res.cloudinary.com/du541igfh/image/upload/v1682772432/Blog%20Portfolio%20Gilbert/Project/mern-penggajian-karyawan/img-15_pzdxsu.png",
  //     "https://res.cloudinary.com/du541igfh/image/upload/v1682772431/Blog%20Portfolio%20Gilbert/Project/mern-penggajian-karyawan/img-16_ven89o.png",
  //     "https://res.cloudinary.com/du541igfh/image/upload/v1682772432/Blog%20Portfolio%20Gilbert/Project/mern-penggajian-karyawan/img-17_wjwedp.png",
  //     "https://res.cloudinary.com/du541igfh/image/upload/v1682772432/Blog%20Portfolio%20Gilbert/Project/mern-penggajian-karyawan/img-18_zpsewd.png",
  //   ],
  //   features: [
  //     "Login Admin",
  //     "Add employee",
  //     "Edit employee",
  //     "Remove employee",
  //     "Add position",
  //     "Edit position",
  //     "Remove position",
  //     "Display data, input attendance, edit attendance and delete employee absences",
  //     "Employee Salary Deduction Setting",
  //     "Display data, input salary data, edit salary data and delete employee salary data",
  //     "Print payroll reports, absences, and payslips",
  //     "Change admin and employee passwords",
  //     "Login Employees/Staff",
  //     "Print employees/staff salary reports from personal accounts",
  //     "404 Page and many more",
  //     "Responsive Design",
  //   ],
  //   technologies: [
  //     "React",
  //     "React Hooks",
  //     "React Icons",
  //     "React Vite",
  //     "Redux",
  //     "Redux Toolkit",
  //     "Tailwind CSS",
  //     "Apexcharts",
  //     "Localforage",
  //     "Match Sorter",
  //     "Axios",
  //     "Node JS",
  //     "Express JS",
  //     "MySQL",
  //     "Cors",
  //     "JWT",
  //     "Bycrypt",
  //     "Cookie Parser",
  //     "Dotenv",
  //     "MySQL 12",
  //     "Nodemon",
  //     "Sequelize",
  //   ],
  //   title: "Employee Salary Management",
  //   description:
  //     "Warehouse website with employee/employee management, add employee and job title options. Employee attendance data setting salary deductions and salary data. Print salary reports, attendance and salary data and many other features.",
  //   category: "business",
  //   liveLink: "https://berthutapea.vercel.app/employee-salary-management",
  //   codeLink: "https://github.com/berthutapea/mern-employee-salary-management",
  // },
  // {
  //   id: 5,
  //   mainImage: "https://res.cloudinary.com/du541igfh/image/upload/v1683869747/Blog%20Portfolio%20Gilbert/Project/mern-student-management-system/img-1_yhedpu.png",
  //   img: [
  //     "https://res.cloudinary.com/du541igfh/image/upload/v1683869747/Blog%20Portfolio%20Gilbert/Project/mern-student-management-system/img-1_yhedpu.png",
  //     "https://res.cloudinary.com/du541igfh/image/upload/v1683869747/Blog%20Portfolio%20Gilbert/Project/mern-student-management-system/img-2_uktrxk.png",
  //     "https://res.cloudinary.com/du541igfh/image/upload/v1683869747/Blog%20Portfolio%20Gilbert/Project/mern-student-management-system/img-3_s1js9i.png",
  //     "https://res.cloudinary.com/du541igfh/image/upload/v1683869747/Blog%20Portfolio%20Gilbert/Project/mern-student-management-system/img-4_sb9ga6.png",
  //     "https://res.cloudinary.com/du541igfh/image/upload/v1683869748/Blog%20Portfolio%20Gilbert/Project/mern-student-management-system/img-5_wrxlr7.png",
  //   ],
  //   features: [
  //     "Add Student",
  //     "Edit Student",
  //     "Remove Student",
  //     "No Student Page",
  //     "Responsive Design",
  //     "404 Page and many more",
  //   ],
  //   technologies: [
  //     "React",
  //     "React Hooks",
  //     "React Router Dom",
  //     "Axios",
  //     "Bootstrap",
  //     "React Icons",
  //     "Sweet Alert2",
  //     "Node JS",
  //     "Express JS",
  //     "Cors",
  //     "Mongoose",
  //     "Dotenv",
  //     "Nodemon",
  //     "MongoDB",
  //   ],
  //   title: "Student Management System",
  //   description:
  //     "Fullstack open source student management system application made with MongoDB, Express, React & Nodejs (MERN)",
  //   category: "business",
  //   liveLink: "https://sttiss.vercel.app/",
  //   codeLink: "https://github.com/berthutapea/mern-student-management-system",
  // },
  // {
  //   id: 6,
  //   mainImage: "https://res.cloudinary.com/du541igfh/image/upload/v1682964283/Blog%20Portfolio%20Gilbert/Project/mario-jump-game/img-2_iwduig.png",
  //   img: [
  //     "https://res.cloudinary.com/du541igfh/image/upload/v1682964283/Blog%20Portfolio%20Gilbert/Project/mario-jump-game/img-1_gpiiro.png",
  //     "https://res.cloudinary.com/du541igfh/image/upload/v1682964283/Blog%20Portfolio%20Gilbert/Project/mario-jump-game/img-2_iwduig.png",
  //     "https://res.cloudinary.com/du541igfh/image/upload/v1682964283/Blog%20Portfolio%20Gilbert/Project/mario-jump-game/img-3_sk2hyn.png",
  //   ],
  //   features: [
  //     "Mobile Responsive",
  //     "Beautiful Animations",
  //     "Rapid Controls",
  //     "High Score",
  //     "Mario Background Music",
  //     "Jump & Game Over Sound Effect",
  //   ],
  //   technologies: [
  //     "React",
  //     "CSS",
  //     "React Hooks",
  //     "React Router",
  //     "React Redux",
  //   ],
  //   title: "Mario Jump",
  //   description:
  //     "Mario Jump is an endless running game inspired by the famous Google Chrome's T-Rex Dinosaur Game 🦖. The game is built entirely with ReactJS ⚛ and Redux Toolkit 🔧.",
  //   category: "game",
  //   liveLink: "https://mariojumpp.vercel.app/",
  //   codeLink: "https://github.com/berthutapea/mario-jump-game",
  // },
  // {
  //   id: 7,
  //   mainImage: "https://res.cloudinary.com/du541igfh/image/upload/v1682944695/Blog%20Portfolio%20Gilbert/Project/bert-quiz/img-3_t6uxoj.png",
  //   img: [
  //     "https://res.cloudinary.com/du541igfh/image/upload/v1682944091/Blog%20Portfolio%20Gilbert/Project/bert-quiz/img-1_gqero4.png",
  //     "https://res.cloudinary.com/du541igfh/image/upload/v1682944091/Blog%20Portfolio%20Gilbert/Project/bert-quiz/img-2_ukjdh2.png",
  //     "https://res.cloudinary.com/du541igfh/image/upload/v1682944695/Blog%20Portfolio%20Gilbert/Project/bert-quiz/img-3_t6uxoj.png",
  //     "https://res.cloudinary.com/du541igfh/image/upload/v1682944091/Blog%20Portfolio%20Gilbert/Project/bert-quiz/img-4_btevir.png",
  //     "https://res.cloudinary.com/du541igfh/image/upload/v1682944091/Blog%20Portfolio%20Gilbert/Project/bert-quiz/img-5_oakjx2.png",
  //     "https://res.cloudinary.com/du541igfh/image/upload/v1682944092/Blog%20Portfolio%20Gilbert/Project/bert-quiz/img-6_pqefy9.png",
  //     "https://res.cloudinary.com/du541igfh/image/upload/v1682944091/Blog%20Portfolio%20Gilbert/Project/bert-quiz/img-7_wfrvb7.png",
  //   ],
  //   features: [
  //     "User registration and login",
  //     "Select the type of question and the difficulty level of the question",
  //     "Juis time is running and after the time is up it stops automatically",
  //     "The final results of the answers answered will be shown",
  //     "Incorrect and correct answer results will be displayed",
  //     "Responsive Design",
  //   ],
  //   technologies: [
  //     "React",
  //     "React Vite",
  //     "Tailwind CSS",
  //     "Firebase Authentication",
  //     "Framer Motion",
  //     "React Firebase Hooks",
  //     "React Icons",
  //   ],
  //   title: "Bert Quiz",
  //   description:
  //     "Fullstack open source quiz application",
  //   category: "personal",
  //   liveLink: "https://bertquiz.vercel.app/",
  //   codeLink: "https://github.com/berthutapea/react-quiz",
  // },
  // {
  //   id: 8,
  //   mainImage: "https://res.cloudinary.com/du541igfh/image/upload/v1683033408/Blog%20Portfolio%20Gilbert/Project/shopify/img-1_q5d6pn.png",
  //   img: [
  //     "https://res.cloudinary.com/du541igfh/image/upload/v1683033408/Blog%20Portfolio%20Gilbert/Project/shopify/img-1_q5d6pn.png",
  //     "https://res.cloudinary.com/du541igfh/image/upload/v1683033411/Blog%20Portfolio%20Gilbert/Project/shopify/img-2_nko9ic.png",
  //     "https://res.cloudinary.com/du541igfh/image/upload/v1683033413/Blog%20Portfolio%20Gilbert/Project/shopify/img-3_rnhbr1.png",
  //     "https://res.cloudinary.com/du541igfh/image/upload/v1683033408/Blog%20Portfolio%20Gilbert/Project/shopify/img-4_ks8lck.png",
  //     "https://res.cloudinary.com/du541igfh/image/upload/v1683033409/Blog%20Portfolio%20Gilbert/Project/shopify/img-5_eotroj.png",
  //     "https://res.cloudinary.com/du541igfh/image/upload/v1683033408/Blog%20Portfolio%20Gilbert/Project/shopify/img-6_fgpzef.png",
  //   ],
  //   features: [
  //     "Mobile Responsive",
  //     "Beautiful Animations",
  //     "Product",
  //     "Pricing",
  //     "Testimonial",
  //     "Contact",
  //   ],
  //   technologies: [
  //     "React",
  //     "React Vite",
  //     "Tailwind CSS",
  //     "Framer Motion",
  //     "React Icons",
  //     "React Hooks",
  //   ],
  //   title: "Shopify",
  //   description:
  //     "Open source landing page shopify application",
  //   category: "personal",
  //   liveLink: "https://shopifyy.vercel.app/",
  //   codeLink: "https://github.com/berthutapea/react-shopify-landing",
  // },
];

export default Items;
